name: Actividad DAW
on: push
jobs:
    test-and-lint:
       runs-on: ubuntu-latest
       steps:
          - 
            name: Copiar código
            uses: actions/checkout@v4
          - 
            name:  Ejecutar requerimientos
            run: pip install -r requirements.txt
          - 
            name: Ejecutart tests
            run: pytest
          -
            name: Lint
            run: ruff check .

    buildear-imagen-docker:
      runs-on: ubuntu-latest
      steps:
       -
        name: Copiar código
        uses: actions/checkout@v4
       - 
        name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.zono32 }}
          password: ${{ secrets.DOCKERHUBTOKEN }}
       -
        name: Build y push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fruizotero/calculadora-back-daw:latest

    build-and-push-github-package:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Copiar código
          uses: actions/checkout@v4
        -
          name: Login en GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.ZONO32 }}
        -
          name: Build image y pushear a Github Packages
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/fruizotero/back-calculadora-template:latest
          
    